# Site settings
title: Claire Labit-Bonis' homepage
description: ACTIA Automotive / LAAS-CNRS Ph.D. student 
email: "clabitbo _at_ laas.fr"
url: "http://beliasus.github.io"
github_username:  beliasus

# Build settings
markdown: kramdown
permalink: pretty

show_downloads: true

theme: jekyll-theme-cayman

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
