# Site settings
title: Claire Labit-Bonis' homepage
baseurl: ""
url: "http://beliasus.github.io"
github_username:  beliasus

# Build settings
markdown: kramdown
permalink: pretty

show_downloads: true

linkedin: true

theme: jekyll-theme-cayman

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
