# Site settings
title: Claire Labit-Bonis
description: ACTIA Automotive / LAAS-CNRS Ph.D. student - clabitbo@laas.fr
url: "http://beliasus.github.io"
github_username:  beliasus

# Build settings
markdown: kramdown
permalink: home

show_downloads: true

theme: jekyll-theme-cayman

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
